services:
  mongo:
    image: mongo
    container_name: teleposter_mongodb
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - mongodb-data:/data/db

  backend:
    build: .
    container_name: teleposter_backend
    restart: unless-stopped
    command: python3 src/main.py
    volumes:
      - media_value:/teleposter/media/
    depends_on:
      - mongo
    env_file:
      - ./.env

  bot:
    build: .
    container_name: teleposter_bot
    restart: unless-stopped
    command: python3 src/bot.py
    depends_on:
      - backend
    env_file:
      - ./.env
    environment:
      - API_URL=http://backend:8000

  frontend:
    build:
      context: ./frontend
    container_name: teleposter_frontend
    volumes:
      - react_build:/teleposter/build/
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=/api/v1/

  nginx:
    image: nginx:latest
    container_name: teleposter_nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - react_build:/usr/share/nginx/html
      - media_value:/var/html/media/
    env_file:
      - ./.env
  

volumes:
  mongodb-data:
  media_value:
  react_build:
