services:
  mongo:
    image: mongo
    container_name: teleposter_mongodb
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - mongodb-data:/data/db

  mongo-express:
    image: mongo-express
    container_name: teleposter_mongo_express
    restart: unless-stopped
    ports:
      - 8081:8081
    depends_on:
      - mongo
    env_file:
      - ./.env

  backend:
    build: .
    container_name: teleposter_backend
    restart: unless-stopped
    command: python3 src/main.py
    volumes:
      - media_value:/teleposter/media/
    depends_on:
      - mongo
    env_file:
      - ./.env
    environment:
      - DEBUG=True
    develop:
      watch: 
        - path: ./requirements.txt
          action: rebuild
        - path: ./src
          target: /teleposter/src
          action: sync

  bot:
    build: .
    container_name: teleposter_bot
    restart: unless-stopped
    command: python3 src/bot.py
    depends_on:
      - backend
    env_file:
      - ./.env
    environment:
      - API_URL=http://backend:8000
    develop:
      watch: 
        - path: ./requirements.txt
          action: rebuild
        - path: ./src/bot
          target: /teleposter/src/bot
          action: sync+restart

  nginx:
    image: nginx:latest
    container_name: teleposter_nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - media_value:/var/html/media/
    env_file:
      - ./.env
  

volumes:
  mongodb-data:
  media_value:
