services:
  mongo:
    image: mongo
    container_name: teleposter_mongodb
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - mongodb-data:/data/db

  mongo-express:
    image: mongo-express
    container_name: teleposter_mongo_express
    restart: unless-stopped
    ports:
      - 8081:8081
    depends_on:
      - mongo
    env_file:
      - ./.env

  backend:
    build: .
    container_name: teleposter_backend
    restart: unless-stopped
    command: python3 src/main.py
    volumes:
      - media_value:/teleposter/media/
    depends_on:
      - mongo
    env_file:
      - ./.env
    develop:
      watch: 
        - path: ./requirements.txt
          action: rebuild
        - path: ./src
          target: /teleposter/src
          action: sync

  frontend:
    build:
      context: ./frontend
    container_name: teleposter_frontend
    volumes:
      - react_build:/teleposter/build/
    depends_on:
      - backend
    develop:
      watch: 
        - path: ./frontend/src
          action: rebuild
        - path: ./frontend/public
          action: rebuild

  nginx:
    image: nginx:latest
    container_name: teleposter_nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - react_build:/usr/share/nginx/html
      - media_value:/var/html/media/
    env_file:
      - ./.env
  

volumes:
  mongodb-data:
  media_value:
  react_build:
